name: bito
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - bison >= 3.4
  - cmake >= 3.19
  - flex
  - make
  - numpy
  - pip
  - pybind11 >= 2.3.0
  - pytest
  - sphinx >= 2.2.1
  - pip:
      - black
      - click
      - docformatter
      - flake8
      - sphinx-click
      - sphinx-rtd-theme
