name: libsbn
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - beagle-lib
  - flex
  - make
  - numpy
  - pip
  - pybind11 >=2.3.0
  - pytest
  - scons
  - pip:
      - enscons
